communications:
  client-api:
    request-queue: communications.request
  queueing:
    destination:
      email: communications.delivery.email
    source: communications.request
  delivery:
    email: communications.delivery.email

spring:
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      max-connections: 10
      enabled: true
