communications:
  client-api:
    request-queue: communications.request
  queueing:
    destination:
      email: communications.delivery.email
      sms: communications.delivery.sms
      push: communications.delivery.push
      iam: communications.delivery.iam
    source: communications.request
  delivery:
    email: communications.delivery.email
    sms: communications.delivery.sms
    push: communications.delivery.push
    iam: communications.delivery.iam

spring:
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      max-connections: 10
      enabled: true
